"""empty message

Revision ID: 8230e7a7a03e
Revises: 5727df02f8bf
Create Date: 2018-02-14 14:49:57.745268

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '8230e7a7a03e'
down_revision = '5727df02f8bf'
branch_labels = None
depends_on = None

game_status = postgresql.ENUM('won', 'in_progress', 'lost', name='game_status')

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    game_status.create(op.get_bind())

    op.add_column('games', sa.Column('score', sa.Integer(), nullable=False))
    op.add_column('games', sa.Column('status', sa.Enum('won', 'in_progress', 'lost', name='game_status'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'status')
    op.drop_column('games', 'score')
    game_status.drop(op.get_bind())
    # ### end Alembic commands ###
